version: "3.9"

services:
  api:
    build: api/.
    container_name: flask-api
    ports:
      - "5000:5000"
    environment:
      APP_DB_HOST: db
      APP_DB_PORT: 5432
      APP_DB_USER: postgres
      APP_DB_PASSWORD: password
      APP_DB_NAME: myapp_db
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  pgdata:
