apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  namespace: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
        - name: flask-api
          image: myflaskapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000 
          env:
            - name: APP_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_HOST
            - name: APP_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PORT
            - name: APP_DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: APP_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: APP_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB

          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          
          livenessProbe:
            httpGet:
              path: /health
              port: 5000 
            initialDelaySeconds: 15 
            periodSeconds: 20     
            failureThreshold: 3    
            timeoutSeconds: 5
            
          readinessProbe:
            httpGet:
              path: /health
              port: 5000 
            initialDelaySeconds: 5  
            periodSeconds: 10       
            failureThreshold: 5     
            timeoutSeconds: 3